---
# Common tasks
- name: add-apt-repository
  apt: pkg=python-software-properties state=installed

- name: install java
  apt: pkg=openjdk-7-jdk state=installed

- name: install unzip
  apt: pkg=unzip state=installed

