---
# Common tasks
- name: add-apt-repository
  apt: pkg=python-software-properties state=installed

- name: install packages
  apt: pkg=$item state=installed
  with_items:
    - openjdk-7-jdk
    - unzip
    - curl

