---
# Jenkins with plugins
- name: Jenkins repo key
  apt_key: url='http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key' state=present
- name: Jenkins repo
  copy: content='deb http://pkg.jenkins-ci.org/debian binary/' dest=/etc/apt/sources.list.d/jenkins.list
  # apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'
- name: Apt update
  apt: update_cache=yes
- name: Jenkins install
  apt: pkg=jenkins state=present
