---
# Jenkins with plugins

# install Jenkins
- name: Jenkins repo key
  apt_key: url='http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key' state=present
- name: Jenkins repo
  copy: content='deb http://pkg.jenkins-ci.org/debian binary/' dest=/etc/apt/sources.list.d/jenkins.list
  # apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'
- name: Apt update
  apt: update_cache=yes
- name: Jenkins install
  apt: pkg=jenkins state=present

# install plugins
- name: install plugins
  get_url: url=http://updates.jenkins-ci.org/download/plugins/$item
           dest=/var/lib/jenkins/plugins/ owner=jenkins group=nogroup
  with_items:
    - git-client/1.0.5/git-client.hpi
    - git/1.3.0/git.hpi
    - artifactory/2.1.5/artifactory.hpi
    - build-pipeline-plugin/1.3.3/build-pipeline-plugin.hpi
    - scm-sync-configuration/0.0.7/scm-sync-configuration.hpi
  notify:
    - restart jenkins
