---
- name: ppa for maven 3
  apt_repository: repo='deb http://ppa.launchpad.net/natecarlson/maven3/ubuntu precise main'
- name: update apt
  apt: update_cache=yes
- name: install maven 3
  apt: pkg=maven3 state=present
- name: link to mvn3
  command: update-alternatives --install /usr/bin/mvn mvn /usr/share/maven3/bin/mvn 3
